title: Merculbir
author: Josile
email: merculbir.josile@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Que va-t-il lui arriver ?

# social links
github_username: spaenleh

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
  - about.md
  - contact.md
minima:
  date_format: "%-d %B %Y"

masthead: /blaz_merculbir.png

theme: minima
